### ISSUE TITLE
Heroku pipeline

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#10]
Setup a Heroku pipeline with following apps:

```
mosaicobackend-dev -> mosaicobackend-preprod -> mosaicobackend-prod
```

- [x] update build system to create dev AND production assets
- [x] point to different files in the templates depending on the environment
- [x] make a new single release branch
- [x] test the pipeline

**Comment by Hiswe** [comment]
@abernier we don't need 2 release branches now.
Can you come with a name of a single release branch please?

**Comment by abernier** [comment]
let say `release` ?

**Comment by Hiswe** [comment]
@abernier ok done

You can test now a pipeline

**Comment by abernier** [comment]
wip https://dashboard.heroku.com/pipelines/d7eea769-6365-42b0-9bd3-c6d9c287831d

**Comment by abernier** [comment]
done
