### ISSUE TITLE
no template by default

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#11]
Un utilisateur venant de deployer une nouvelle instance n'a pas de template a disposition pour tester l'editeur...

Il devra :
- creer un groupe
- creer un template

avant de pouvoir utiliser l'editeur...

**Comment by abernier** [comment]
Ne pourrait-on pas réfléchir a des solutions comme guider l'utilisateur dans ses premiers pas, comme un tutorial par ex

**Comment by abernier** [comment]
Pour adresser le probleme progressivement :
1. bien documenter cela dans un "Quick-Start" utilisateur
2. présenter une liste d'upload "rapide" de templates (Versafix et TEDC15) pour simplifier (necessite un peu d'UX)
![image](https://user-images.githubusercontent.com/76580/28519983-0799a8f8-706e-11e7-99f7-8fc6062d098e.png)

**Comment by Hiswe** [comment]
@abernier il faudrait améliorer l'UI.
Des idées ?

![screen shot 2017-07-28 at 15 56 57](https://user-images.githubusercontent.com/96121/28710250-829e0cd2-73ad-11e7-9a57-96fec555dbb9.png)

**Comment by abernier** [comment]
c'est goodenough pour l'instant je pense, on peut a mon avis fermer le ticket.

Precision, si j'upload un html, la zone "prebuilt" disparait ?

**Comment by Hiswe** [comment]
@abernier je peux le faire disparaitre s'il y a déjà du code HTML présent

**Comment by abernier** [comment]
ca me va ;)

**Comment by Hiswe** [comment]
@abernier Ça donne ça en version finale :

![screen shot 2017-07-28 at 16 23 07](https://user-images.githubusercontent.com/96121/28711271-3d6f890c-73b1-11e7-9642-9d907495a927.png)

![screen shot 2017-07-28 at 16 23 31](https://user-images.githubusercontent.com/96121/28711272-3f1ee658-73b1-11e7-8374-324c5bc458d7.png)

Je vais pousser ça en release, tu testeras et fermeras si c'est bon pour toi

**Comment by abernier** [comment]
ok envoie ! ;)

**Comment by Hiswe** [comment]
@abernier https://github.com/goodenough/mosaico-backend/releases/tag/release-0.0.16

**Comment by abernier** [comment]
good 👍
