### ISSUE TITLE
Screencast

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#13]
Flow: cf. https://github.com/goodenough/mosaico-backend/issues/13#issuecomment-317656832

mov to gif: https://gist.github.com/dergachev/4627207#instructions

**Comment by Hiswe** [comment]
- login in the admin
- go to group page
- create a group
- click on *new template*
- upload the content of versafix (HTML and every images NOT edres)
- save the changes 
- click on *generate previews*
- wait for this to happen (can take some time)
- go back in the group viathe left menu
- click on *new user*
- create a user 
- send the activation link
- deconnect from admin
- check the mail and click on the connection button
- set your new password
- go to the template page
- click on versafix
- drag some blocks and upload some images
- save the mailing
- test the mailing (send email test)
- check the test mail
- go back to the editor
- download the email
- go to your download folder
- uncompress and check the folder structure
- open the mailing and check it
- go back to the editor
- go the mailing listing (letter icon upper left)

**Comment by abernier** [comment]
done https://youtu.be/sLzZq3cXDi0
