### ISSUE TITLE
supprimer `HEROKU_APP_NAME ` du app.json

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#14]
et essayer de ré-utiliser le nom de l'application heroku directement
![image](https://user-images.githubusercontent.com/76580/28523462-d9fbb8e6-707c-11e7-8024-13a7f3f9b424.png)

cf : 
- https://stackoverflow.com/questions/12570579/how-to-get-heroku-app-name-url-from-inside-the-app
- https://devcenter.heroku.com/articles/dyno-metadata

**Comment by Hiswe** [comment]
@abernier Malheureusement je n'ai pas moyen d'automatiser ça dans le app.json ([source](https://stackoverflow.com/questions/37570681/enable-heroku-labs-feature-in-heroku-review-apps#answer-37571569))
Ça passe toujours par une ligne de commande… 

soit : 

```
heroku labs:enable runtime-dyno-metadata -a <app name>
```

ou 

```
heroku config:set HEROKU_URL=$(heroku info -s | grep web_url | cut -d= -f2)
```

Donc je pense qu'il faudrait laisser le champ tel quel pour plus de simplicité. Même s'il faudrait sans doute plus d'explications

**Comment by Hiswe** [comment]
Par contre il faudrait changer le nom de la variable pour suivre [les recommandations de heroku](https://devcenter.heroku.com/articles/dyno-metadata)

**Comment by Hiswe** [comment]
@abernier je te laisse décider de la marche à suivre pour la suite

**Comment by abernier** [comment]
ok, je ne pense a aucune solution de mon coté non plus, on laisse tel quel du coup meme si pas pratique d'avoir a copier/coller le nom
