### ISSUE TITLE
HEROKU – add deploy button

### ISSUE THREAD

**Issue by Hiswe** [goodenough/mosaico-backend#2]
- [x] deploy a compiled branch
- [x] Handle S3
- [x] Fix versions of `node_modules`

**Comment by abernier** [comment]
https://devcenter.heroku.com/articles/heroku-button

**Comment by abernier** [comment]
For S3, as discussed with @Hiswe, maybe the most immediate solution will be to ask user for his S3 URI, letting him entirely responsible for creating his own bucket.

Tomorrow, we can find a more assisted solution, in order the user has not to deal with (ideally a free S3 addons)...

**Comment by abernier** [comment]
Hey,

Un truc que je n'ai peut-etre pas saisi mais qd je regarde la branche [stage](https://github.com/goodenough/mosaico-backend/tree/stage) je ne vois pas le dossier `node_modules` mais pas non plus de `npmshrinkwrap.json`... du coup comment etre sur qu'Heroku va bien `npm install`er récursivement les mêmes versions de tous les packages ?

Doit-on créer un ticket pour le shrinkwrap ?

Je sais que tu m'as dit qu'npm le gerait plus ou moins nativement maintenant, mais a partir de quelle version ? Tu sais du coup comment ca marche ?

**Comment by Hiswe** [comment]
@abernier pour l'instant ce n'est pas géré.

J'aimerai tester le code avec node 8 et sa nouvelle version de NPM qui gère automatiquement ça.
Dans le cas contraire il faudra faire un shrinkwrap.

**Comment by Hiswe** [comment]
@abernier montée de version faite pour node. On est passé en 8.2.1

On a donc un [package-lock.json](https://docs.npmjs.com/files/package-lock.json) qui réponds à la problématique des node_modules.

à toi donc de voir où on en est sur ce ticket
