### ISSUE TITLE
THEME – brand customization

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#3]
- [x] give colors to @Hiswe to update UI
- [x] replace every color references by CSS custom properties
- [x] colors should be specified in Heroku config
- [x] remove any logos and replace it by a text
- [x] favicon

**Comment by Hiswe** [comment]
@abernier J'ai repris les couleurs de https://getmdl.io/customize/index.html

ce qui donne :

![mailing-list](https://user-images.githubusercontent.com/96121/28106798-85cde5ee-670f-11e7-98f0-4ab48ccd60e7.jpg)

![editor](https://user-images.githubusercontent.com/96121/28106801-896de960-670f-11e7-925f-b4ab82535366.jpg)

**Comment by abernier** [comment]
ok great, et est-ce qu'on peut les overrider en conf ou chiant avec la compil ?

**Comment by Hiswe** [comment]
Ça donne ça en config serveur :

```js
"brand": {
    "color-primary": "rgb(233,30,99)",
    "color-primary-contrast": "white",
    "color-accent": "#3f51b5",
    "color-accent-contrast": "white"
},
```

dans les exemples ça donne : 

- primary = bleu
- primary-contrast = blanc (text sur le bleu)
- accent = rose
- accent-contrast = blanc (text sur le accent)

**Comment by Hiswe** [comment]
@abernier pour le favicon j'en ai mis un par défaut. 
Il faut plus ?

**Comment by abernier** [comment]
good
