### ISSUE TITLE
Demo link has given no credentials and no way to register

### ISSUE THREAD

**Issue by davidfurlong** [goodenough/mosaico-backend#46]
I can't find credentials nor a way to sign up on the demo

**Comment by Hiswe** [comment]
Hi @davidfurlong,

The demo is almost only here to see that you can deploy the app on heroku :/ 
The way this back-office is done is that a super-admin create/activate all the user accounts: no way for a user to self-register.

Two solutions from here:
- If you have an [Heroku](https://www.heroku.com/) account and an [Amazon S3](https://aws.amazon.com/s3/?nc1=h_ls) one just try the deploy button! you will be able to configure the credentials there.
- If not you can still deploy it locally to have a preview of how is it working :)

If you have any trouble installing with one of those solutions, let me know!

**Comment by davidfurlong** [comment]
@Hiswe I managed to get it running locally, but I think people can take your word that it 'can be deployed to heroku' given heroku is a cloud provider. Calling it a demo wasted my time trying to figure out how to access it, and this probably happens to others as well

**Comment by Hiswe** [comment]
@davidfurlong Thank for your feedback.

I will update the documentation :)
