### ISSUE TITLE
IMG - absolute url

### ISSUE THREAD

**Issue by ivett-f** [goodenough/mosaico-backend#47]
Hi,

We have deployed mosaico-backend on Heroku with your "Heroku Button". Everything is working great. I have just one question. When we are importing img from galery <img dato-ko-editable="Image.src"...in the dowloaded zip code img src is with relative(local) url address. Is it possible to download html with absolute address as is on AWS?

**Comment by Hiswe** [comment]
@ivett-f Hi,
thanks for using this backend :)

It's not possible to have the absolute url while downloading.
From a previous [ticket](https://github.com/goodenough/mosaico-backend/issues/45)
:
> The reason behind this is that you usually upload the archive file in a mail service.
They will manage their own CDN and don't impact yours.
>
> But the test mail button will send you the HTML with the images linked to your own CDN.

If you follow all the answers, you should find a solution to implement the behavior you want by modifying the code 🙂

**Comment by ivinkaf** [comment]
Hi Hiswe,

thank you! Could you please help me to identified the origin url? 

3.Now extract the https://github.com/ part so from the above example you'd be left with https://github.com/jamesward/heroku-connect-phone-change (<YOUR-REPO-URL> ).

https://help.heroku.com/XOBUHLKQ/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository-when-using-heroku-git-clone

Have a nice day!
Ivet

**Comment by Hiswe** [comment]
I don't understand your question

**Comment by ivinkaf** [comment]
Nevermind...I have one more question, when I try to run "git push heroku" command, I get the error message: "EINVRES Request to https://bower.herokuapp.com/packages/jquery-file-upload failed with 502". Could you please help me where (in which file) should I add registry: "https://registry.bower.io"

**Comment by Hiswe** [comment]
@ivinkaf I'm currently migrating the application to Mosaico v0.17 which remove the use of bower.
So I won't dig into this issue :)

**Comment by ivett-f** [comment]
Hi Hiswe,

Do you know when should be Mosaico17.0 available?
Thanks
Ivet

**Comment by Hiswe** [comment]
@ivett-f Unfortunately no release date for now…

Migration is done but while doing so I've seen that I messed up with the “device preview” function.
I try to add this functionality for small device for now…

So I'll wait to fix that to make a release

**Comment by Hiswe** [comment]
@ivinkaf support for download only HTML with images pointing to the CDN done
@ivett-f the backend now embed mosaico 0.17.4
