### ISSUE TITLE
(developer|local)-first

### ISSUE THREAD

**Issue by abernier** [goodenough/mosaico-backend#9]
The project is intended to be **developer-first** and also **local-first** -- in effective, there is little chance a sales manager install the project on his machine or a developer doesn't want to test on a dev environment before a production one.

Therefore, [README](https://github.com/goodenough/mosaico-backend/blob/master/README.md), install commands...etc should be written/designed with this in mind.

For example, `npm run build` should not be for building a production server but rather a developer server.

Idem for `npm start` and so on...

@Hiswe can you review the npm scripts in that sense ?

**Comment by Hiswe** [comment]
@abernier We need to know what port we should use in default config.

- 7000 for livereload 
- or 3000

**Comment by Hiswe** [comment]
@abernier I mean the default host. 
In my opinion should always be `localhost:3000` and the doc should mention that livereload could be enabled in dev if you set your config to `host: locslhost:7000` and then go to localhost:7000 in your browser

**Comment by abernier** [comment]
I agree for default `localhost:3000` host.
